image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_RELEASE_IMAGE: $CI_DOCKER_REPOSITORY:latest
  CONTAINER_RELEASE_TAGGED_IMAGE: $CI_DOCKER_REPOSITORY:$CI_COMMIT_TAG

before_script:
  - docker login -u $CI_DOCKER_HUB_USER -p $CI_DOCKER_HUB_PASSWORD hub.docker.com

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --no-cache -t $CI_DOCKER_REPOSITORY .
#    - docker run $CI_DOCKER_REPOSITORY /script/to/run/tests

deploy_development:
  stage: deploy
  script:
    - docker tag $CI_DOCKER_REPOSITORY $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - development

deploy_master:
  stage: deploy
  script:
    - docker tag $CI_DOCKER_REPOSITORY $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy_tags:
  stage: deploy
  script:
    - docker tag $CI_DOCKER_REPOSITORY $CONTAINER_RELEASE_TAGGED_IMAGE
    - docker push $CONTAINER_RELEASE_TAGGED_IMAGE
  only:
    - tags
